server:
  port: 8080
spring:
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /image/**
  web:
    resources:
      static-locations:
        - file:///D:/重装前桌面代码内容/暑期实训_2/pictures/medical
  datasource:
    url: jdbc:mysql://localhost:3306/medical?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&characterSetResults=utf8mb4
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
pagehelper:
  reasonable: true
  support-methods-arguments: true
  helper-dialect: mysql
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.qust.task.entity
  configuration:
    map-underscore-to-camel-case: true